---
- hosts: dev 
  tasks: 
        - name: Download tomcat on target host 
          get_url:
                url: "{{ tomcat_download_url }}"
                dest: "{{ tomcat_install_dir }}"
                mode: '0755'

        - name: Create tomcat directory if not exist
          ansible.builtin.file:
                   path: "{{ tomcat_install_dir }}/tomcat"
                   state: directory
                   mode: '0755'

        - name: extract tomcat file to target host 
          ansible.builtin.unarchive:
                src: "{{ tomcat_install_dir }}/apache-tomcat-{{tomcat_version}}.tar.gz"
                dest: "{{ tomcat_install_dir }}/tomcat"
                remote_src: yes

        - name: Check and update tomcat port to 9089
          ansible.builtin.lineinfile:
                  path: "{{ tomcat_install_dir }}/tomcat/apache-tomcat-{{tomcat_version}}/conf/server.xml" 
                  search_string: '    <Connector port="8080" protocol="HTTP/1.1"'
                  line: '    <Connector port="{{ tomcat_port }}" protocol="HTTP/1.1"'      
                  
        - name: Start tomcat on host machine
          ansible.builtin.shell: "./startup.sh && ps -aef | grep tomcat"
          args:
                            chdir: "{{ tomcat_install_dir }}/tomcat/apache-tomcat-{{ tomcat_version }}/bin" 
          register: results 

        - debug:
                var: results
